# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_coding.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogCoding(object):
    def setupUi(self, dialogCoding):
        dialogCoding.setObjectName(_fromUtf8("dialogCoding"))
        dialogCoding.resize(630, 430)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        dialogCoding.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../solitonIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogCoding.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(dialogCoding)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonCodingOK = QtGui.QPushButton(dialogCoding)
        self.buttonCodingOK.setObjectName(_fromUtf8("buttonCodingOK"))
        self.horizontalLayout.addWidget(self.buttonCodingOK)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(dialogCoding)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioCoding3 = QtGui.QRadioButton(self.groupBox)
        self.radioCoding3.setObjectName(_fromUtf8("radioCoding3"))
        self.gridLayout_3.addWidget(self.radioCoding3, 3, 0, 1, 1)
        self.radioCoding2 = QtGui.QRadioButton(self.groupBox)
        self.radioCoding2.setChecked(True)
        self.radioCoding2.setObjectName(_fromUtf8("radioCoding2"))
        self.gridLayout_3.addWidget(self.radioCoding2, 1, 0, 1, 1)
        self.editCode = QtGui.QLineEdit(self.groupBox)
        self.editCode.setEnabled(False)
        self.editCode.setObjectName(_fromUtf8("editCode"))
        self.gridLayout_3.addWidget(self.editCode, 4, 0, 1, 1)
        self.radioCoding1 = QtGui.QRadioButton(self.groupBox)
        self.radioCoding1.setChecked(False)
        self.radioCoding1.setObjectName(_fromUtf8("radioCoding1"))
        self.gridLayout_3.addWidget(self.radioCoding1, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(dialogCoding)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioGap2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioGap2.setObjectName(_fromUtf8("radioGap2"))
        self.gridLayout_5.addWidget(self.radioGap2, 1, 0, 1, 1)
        self.radioGap1 = QtGui.QRadioButton(self.groupBox_2)
        self.radioGap1.setChecked(True)
        self.radioGap1.setObjectName(_fromUtf8("radioGap1"))
        self.gridLayout_5.addWidget(self.radioGap1, 0, 0, 1, 1)
        self.radioGap3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioGap3.setObjectName(_fromUtf8("radioGap3"))
        self.gridLayout_5.addWidget(self.radioGap3, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.stackedWidget = QtGui.QStackedWidget(dialogCoding)
        self.stackedWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(400, 400))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.imageComponents = QtGui.QLabel(self.page)
        self.imageComponents.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.imageComponents.setMinimumSize(QtCore.QSize(0, 0))
        self.imageComponents.setMaximumSize(QtCore.QSize(400, 400))
        self.imageComponents.setText(_fromUtf8(""))
        self.imageComponents.setPixmap(QtGui.QPixmap(_fromUtf8("../components3.png")))
        self.imageComponents.setScaledContents(True)
        self.imageComponents.setObjectName(_fromUtf8("imageComponents"))
        self.label1Gap1 = QtGui.QLabel(self.page)
        self.label1Gap1.setGeometry(QtCore.QRect(160, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label1Gap1.setFont(font)
        self.label1Gap1.setScaledContents(False)
        self.label1Gap1.setObjectName(_fromUtf8("label1Gap1"))
        self.label2Gap1 = QtGui.QLabel(self.page)
        self.label2Gap1.setGeometry(QtCore.QRect(250, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label2Gap1.setFont(font)
        self.label2Gap1.setScaledContents(False)
        self.label2Gap1.setObjectName(_fromUtf8("label2Gap1"))
        self.label3Gap1 = QtGui.QLabel(self.page)
        self.label3Gap1.setGeometry(QtCore.QRect(330, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label3Gap1.setFont(font)
        self.label3Gap1.setScaledContents(False)
        self.label3Gap1.setObjectName(_fromUtf8("label3Gap1"))
        self.label1Gap2 = QtGui.QLabel(self.page)
        self.label1Gap2.setGeometry(QtCore.QRect(130, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label1Gap2.setFont(font)
        self.label1Gap2.setScaledContents(False)
        self.label1Gap2.setObjectName(_fromUtf8("label1Gap2"))
        self.label2Gap2 = QtGui.QLabel(self.page)
        self.label2Gap2.setGeometry(QtCore.QRect(250, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label2Gap2.setFont(font)
        self.label2Gap2.setScaledContents(False)
        self.label2Gap2.setObjectName(_fromUtf8("label2Gap2"))
        self.label3Gap2 = QtGui.QLabel(self.page)
        self.label3Gap2.setGeometry(QtCore.QRect(250, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label3Gap2.setFont(font)
        self.label3Gap2.setScaledContents(False)
        self.label3Gap2.setObjectName(_fromUtf8("label3Gap2"))
        self.label4Gap2 = QtGui.QLabel(self.page)
        self.label4Gap2.setGeometry(QtCore.QRect(250, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label4Gap2.setFont(font)
        self.label4Gap2.setScaledContents(False)
        self.label4Gap2.setObjectName(_fromUtf8("label4Gap2"))
        self.label5Gap2 = QtGui.QLabel(self.page)
        self.label5Gap2.setGeometry(QtCore.QRect(350, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label5Gap2.setFont(font)
        self.label5Gap2.setScaledContents(False)
        self.label5Gap2.setObjectName(_fromUtf8("label5Gap2"))
        self.label1Gap3 = QtGui.QLabel(self.page)
        self.label1Gap3.setGeometry(QtCore.QRect(120, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label1Gap3.setFont(font)
        self.label1Gap3.setScaledContents(False)
        self.label1Gap3.setObjectName(_fromUtf8("label1Gap3"))
        self.label2Gap3 = QtGui.QLabel(self.page)
        self.label2Gap3.setGeometry(QtCore.QRect(260, 0, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label2Gap3.setFont(font)
        self.label2Gap3.setScaledContents(False)
        self.label2Gap3.setObjectName(_fromUtf8("label2Gap3"))
        self.label3Gap3 = QtGui.QLabel(self.page)
        self.label3Gap3.setGeometry(QtCore.QRect(270, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label3Gap3.setFont(font)
        self.label3Gap3.setScaledContents(False)
        self.label3Gap3.setObjectName(_fromUtf8("label3Gap3"))
        self.label4Gap3 = QtGui.QLabel(self.page)
        self.label4Gap3.setGeometry(QtCore.QRect(220, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label4Gap3.setFont(font)
        self.label4Gap3.setScaledContents(False)
        self.label4Gap3.setObjectName(_fromUtf8("label4Gap3"))
        self.label5Gap3 = QtGui.QLabel(self.page)
        self.label5Gap3.setGeometry(QtCore.QRect(190, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label5Gap3.setFont(font)
        self.label5Gap3.setScaledContents(False)
        self.label5Gap3.setObjectName(_fromUtf8("label5Gap3"))
        self.label6Gap3 = QtGui.QLabel(self.page)
        self.label6Gap3.setGeometry(QtCore.QRect(250, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label6Gap3.setFont(font)
        self.label6Gap3.setScaledContents(False)
        self.label6Gap3.setObjectName(_fromUtf8("label6Gap3"))
        self.label7Gap3 = QtGui.QLabel(self.page)
        self.label7Gap3.setGeometry(QtCore.QRect(360, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label7Gap3.setFont(font)
        self.label7Gap3.setScaledContents(False)
        self.label7Gap3.setObjectName(_fromUtf8("label7Gap3"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_8.addWidget(self.stackedWidget, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 10, 1, 1)

        self.retranslateUi(dialogCoding)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialogCoding)

    def retranslateUi(self, dialogCoding):
        dialogCoding.setWindowTitle(_translate("dialogCoding", "Coding", None))
        self.buttonCodingOK.setText(_translate("dialogCoding", "OK", None))
        self.groupBox.setTitle(_translate("dialogCoding", "Coding alphabet", None))
        self.radioCoding3.setText(_translate("dialogCoding", "Custom", None))
        self.radioCoding2.setText(_translate("dialogCoding", "Default", None))
        self.radioCoding1.setText(_translate("dialogCoding", "Convenient", None))
        self.groupBox_2.setTitle(_translate("dialogCoding", "Gap", None))
        self.radioGap2.setText(_translate("dialogCoding", "Gap2", None))
        self.radioGap1.setText(_translate("dialogCoding", "Gap1", None))
        self.radioGap3.setText(_translate("dialogCoding", "Gap3", None))
        self.label1Gap1.setText(_translate("dialogCoding", "1", None))
        self.label2Gap1.setText(_translate("dialogCoding", "2", None))
        self.label3Gap1.setText(_translate("dialogCoding", "3", None))
        self.label1Gap2.setText(_translate("dialogCoding", "1", None))
        self.label2Gap2.setText(_translate("dialogCoding", "2", None))
        self.label3Gap2.setText(_translate("dialogCoding", "3", None))
        self.label4Gap2.setText(_translate("dialogCoding", "4", None))
        self.label5Gap2.setText(_translate("dialogCoding", "5", None))
        self.label1Gap3.setText(_translate("dialogCoding", "1", None))
        self.label2Gap3.setText(_translate("dialogCoding", "2", None))
        self.label3Gap3.setText(_translate("dialogCoding", "3", None))
        self.label4Gap3.setText(_translate("dialogCoding", "4", None))
        self.label5Gap3.setText(_translate("dialogCoding", "5", None))
        self.label6Gap3.setText(_translate("dialogCoding", "6", None))
        self.label7Gap3.setText(_translate("dialogCoding", "7", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dialogCoding = QtGui.QDialog()
    ui = Ui_dialogCoding()
    ui.setupUi(dialogCoding)
    dialogCoding.show()
    sys.exit(app.exec_())

