# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_params.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogParams(object):
    def setupUi(self, dialogParams):
        dialogParams.setObjectName(_fromUtf8("dialogParams"))
        dialogParams.resize(475, 422)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../solitonIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogParams.setWindowIcon(icon)
        dialogParams.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(dialogParams)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(dialogParams)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.spinBox_strip = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_strip.setDecimals(6)
        self.spinBox_strip.setMinimum(1e-06)
        self.spinBox_strip.setMaximum(100.0)
        self.spinBox_strip.setSingleStep(0.1)
        self.spinBox_strip.setProperty("value", 1.0)
        self.spinBox_strip.setObjectName(_fromUtf8("spinBox_strip"))
        self.gridLayout_5.addWidget(self.spinBox_strip, 12, 1, 1, 1)
        self.spinBox_h = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_h.setEnabled(False)
        self.spinBox_h.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_h.setAutoFillBackground(False)
        self.spinBox_h.setReadOnly(True)
        self.spinBox_h.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_h.setDecimals(12)
        self.spinBox_h.setMaximum(1.0)
        self.spinBox_h.setSingleStep(0.001)
        self.spinBox_h.setObjectName(_fromUtf8("spinBox_h"))
        self.gridLayout_5.addWidget(self.spinBox_h, 5, 1, 1, 1)
        self.spinBoxMu = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxMu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBoxMu.setDecimals(6)
        self.spinBoxMu.setMinimum(-100.0)
        self.spinBoxMu.setMaximum(100.0)
        self.spinBoxMu.setSingleStep(0.001)
        self.spinBoxMu.setProperty("value", 1.0)
        self.spinBoxMu.setObjectName(_fromUtf8("spinBoxMu"))
        self.gridLayout_5.addWidget(self.spinBoxMu, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 12, 0, 1, 1)
        self.spinBox_n = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_n.setMinimum(5)
        self.spinBox_n.setMaximum(80)
        self.spinBox_n.setSingleStep(1)
        self.spinBox_n.setProperty("value", 10)
        self.spinBox_n.setObjectName(_fromUtf8("spinBox_n"))
        self.gridLayout_5.addWidget(self.spinBox_n, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 5, 0, 1, 1)
        self.spinBoxM = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxM.setMinimum(1)
        self.spinBoxM.setMaximum(20)
        self.spinBoxM.setProperty("value", 3)
        self.spinBoxM.setObjectName(_fromUtf8("spinBoxM"))
        self.gridLayout_5.addWidget(self.spinBoxM, 7, 1, 1, 1)
        self.spinBoxV0 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxV0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBoxV0.setDecimals(6)
        self.spinBoxV0.setMinimum(0.0)
        self.spinBoxV0.setMaximum(500.0)
        self.spinBoxV0.setSingleStep(0.001)
        self.spinBoxV0.setProperty("value", 6.0)
        self.spinBoxV0.setObjectName(_fromUtf8("spinBoxV0"))
        self.gridLayout_5.addWidget(self.spinBoxV0, 1, 1, 1, 1)
        self.spinBoxK = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxK.setMinimum(1)
        self.spinBoxK.setMaximum(20)
        self.spinBoxK.setProperty("value", 3)
        self.spinBoxK.setObjectName(_fromUtf8("spinBoxK"))
        self.gridLayout_5.addWidget(self.spinBoxK, 8, 1, 1, 1)
        self.spinBox_m = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_m.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_m.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_m.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_m.setWrapping(False)
        self.spinBox_m.setFrame(True)
        self.spinBox_m.setMinimum(16)
        self.spinBox_m.setMaximum(4096)
        self.spinBox_m.setProperty("value", 32)
        self.spinBox_m.setObjectName(_fromUtf8("spinBox_m"))
        self.gridLayout_5.addWidget(self.spinBox_m, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.spinBoxL = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxL.setEnabled(False)
        self.spinBoxL.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBoxL.setReadOnly(True)
        self.spinBoxL.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxL.setDecimals(12)
        self.spinBoxL.setMinimum(0.0)
        self.spinBoxL.setMaximum(500.0)
        self.spinBoxL.setSingleStep(1.0)
        self.spinBoxL.setProperty("value", 0.0)
        self.spinBoxL.setObjectName(_fromUtf8("spinBoxL"))
        self.gridLayout_5.addWidget(self.spinBoxL, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 8, 0, 1, 1)
        self.spinBox_fg = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_fg.setDecimals(6)
        self.spinBox_fg.setMinimum(1e-06)
        self.spinBox_fg.setMaximum(0.1)
        self.spinBox_fg.setSingleStep(0.001)
        self.spinBox_fg.setProperty("value", 0.001)
        self.spinBox_fg.setObjectName(_fromUtf8("spinBox_fg"))
        self.gridLayout_5.addWidget(self.spinBox_fg, 11, 1, 1, 1)
        self.spinBox_fi = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_fi.setDecimals(6)
        self.spinBox_fi.setMinimum(1e-06)
        self.spinBox_fi.setMaximum(0.1)
        self.spinBox_fi.setSingleStep(0.001)
        self.spinBox_fi.setProperty("value", 0.001)
        self.spinBox_fi.setObjectName(_fromUtf8("spinBox_fi"))
        self.gridLayout_5.addWidget(self.spinBox_fi, 10, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 10, 0, 1, 1)
        self.spinBoxPrecision = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxPrecision.setMaximum(1000000)
        self.spinBoxPrecision.setProperty("value", 400)
        self.spinBoxPrecision.setObjectName(_fromUtf8("spinBoxPrecision"))
        self.gridLayout_5.addWidget(self.spinBoxPrecision, 9, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 7, 0, 1, 1)
        self.spinBoxO = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxO.setEnabled(False)
        self.spinBoxO.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxO.setDecimals(12)
        self.spinBoxO.setMaximum(1.0)
        self.spinBoxO.setSingleStep(0.001)
        self.spinBoxO.setObjectName(_fromUtf8("spinBoxO"))
        self.gridLayout_5.addWidget(self.spinBoxO, 6, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 11, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonParamsOK = QtGui.QPushButton(dialogParams)
        self.buttonParamsOK.setObjectName(_fromUtf8("buttonParamsOK"))
        self.horizontalLayout.addWidget(self.buttonParamsOK)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(dialogParams)
        QtCore.QMetaObject.connectSlotsByName(dialogParams)

    def retranslateUi(self, dialogParams):
        dialogParams.setWindowTitle(_translate("dialogParams", "Parameters", None))
        self.groupBox_2.setTitle(_translate("dialogParams", "Choose appropriate parameters", None))
        self.label_3.setText(_translate("dialogParams", "L=pi*n", None))
        self.label_7.setText(_translate("dialogParams", "n", None))
        self.label_12.setText(_translate("dialogParams", "initial interval of scanning", None))
        self.label_5.setText(_translate("dialogParams", "<html><head/><body><p>m</p></body></html>", None))
        self.label_4.setText(_translate("dialogParams", "<html><head/><body><p>h=pi/m</p></body></html>", None))
        self.label.setText(_translate("dialogParams", "mu", None))
        self.label_2.setText(_translate("dialogParams", "V0", None))
        self.label_9.setText(_translate("dialogParams", "K", None))
        self.label_10.setText(_translate("dialogParams", "step for rough scanning of h-strip", None))
        self.label_6.setText(_translate("dialogParams", "gmpy2 bits", None))
        self.label_13.setText(_translate("dialogParams", "total precision O(h^4)", None))
        self.label_8.setText(_translate("dialogParams", "M", None))
        self.label_11.setText(_translate("dialogParams", "step for robust scanning of h-strip", None))
        self.buttonParamsOK.setText(_translate("dialogParams", "OK", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dialogParams = QtGui.QDialog()
    ui = Ui_dialogParams()
    ui.setupUi(dialogParams)
    dialogParams.show()
    sys.exit(app.exec_())

